import Zurg from '../assets/tree-736885__480.jpg'

export default [
    {
        id:1,
        img:Zurg,
        title:'TITLE1',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        description1:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis,beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earumquibusdam fugiat omnis, vitae.',
        description2:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        description3:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        
    },
    {
        id:2,
        img:Zurg,
        title:'TITLE2',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        description1:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis,beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earumquibusdam fugiat omnis, vitae.',
        description2:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        description3:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
       
    },
    {
        id:3,
        img:Zurg,
        title:'TITLE3',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        description1:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis,beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earumquibusdam fugiat omnis, vitae.',
        description2:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
        description3:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum omnis, eligendi, pariatur voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, assumenda explicabo reprehenderit? voluptatibus ad beatae repellendus sunt amet sed commodi harum? Maiores dolores saepe porro alias quam dolorem accusamus earum quibusdam fugiat omnis, vitae.',
    }
]                                                                                                        

